# Site settings
title: newcome personal blog 
email: lkbycn1998@gmail.com
description: > #刘康的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lvsunlingling.github.io/" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
github_username:  almostlie

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: newcome
  email: lkbycn1998@gmail.com
  link: https://almostlie.github.io/
  github: https://github.com/almostlie
title:  newcome personal blog                            

# avatar头像及Favicon
avatar: https://avatars3.githubusercontent.com/u/26787763?s=460&v=4
#favicon: https://avatars3.githubusercontent.com/u/26787763?s=460&v=4

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器
